# Generated by Django 3.2.9 on 2021-11-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_ingredient_ingredientrecipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
